files:
  - source: /bundles/org.openhab.ui/web/src/assets/i18n/**/en.json
    translation: /%original_path%/%two_letters_code%.json
  - source: /bundles/**/i18n/**/*.properties
    ignore:
      - /bundles/**/i18n/**/*_*.properties
    translation: /%original_path%/%file_name%_%two_letters_code%.properties
