// note: this file is generated and should not be edited by hand

export enum Action {
  navigate = 'navigate',
  command = 'command',
  toggle = 'toggle',
  options = 'options',
  rule = 'rule',
  popup = 'popup',
  popover = 'popover',
  sheet = 'sheet',
  photos = 'photos',
  group = 'group',
  analyzer = 'analyzer',
  url = 'url',
  http = 'http',
  variable = 'variable'
}

export enum ActionHttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE'
}

export enum ActionPageTransition {
  f7Circle = 'f7-circle',
  f7Cover = 'f7-cover',
  f7CoverV = 'f7-cover-v',
  f7Dive = 'f7-dive',
  f7Fade = 'f7-fade',
  f7Flip = 'f7-flip',
  f7Parallax = 'f7-parallax',
  f7Push = 'f7-push'
}

export enum ActionAnalyzerChartType {
  none = '',
  day = 'day',
  isoWeek = 'isoWeek',
  month = 'month',
  year = 'year'
}

export enum ActionAnalyzerCoordSystem {
  time = 'time',
  aggregate = 'aggregate',
  calendar = 'calendar'
}

export enum ActionAnalyzerAggregation {
  average = 'average',
  sum = 'sum',
  min = 'min',
  max = 'max',
  first = 'first',
  last = 'last',
  diffFirst = 'diff_first',
  diffLast = 'diff_last'
}

export enum Taphold_action {
  navigate = 'navigate',
  command = 'command',
  toggle = 'toggle',
  options = 'options',
  rule = 'rule',
  popup = 'popup',
  popover = 'popover',
  sheet = 'sheet',
  photos = 'photos',
  group = 'group',
  analyzer = 'analyzer',
  url = 'url',
  http = 'http',
  variable = 'variable'
}

export enum Taphold_actionHttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE'
}

export enum Taphold_actionPageTransition {
  f7Circle = 'f7-circle',
  f7Cover = 'f7-cover',
  f7CoverV = 'f7-cover-v',
  f7Dive = 'f7-dive',
  f7Fade = 'f7-fade',
  f7Flip = 'f7-flip',
  f7Parallax = 'f7-parallax',
  f7Push = 'f7-push'
}

export enum Taphold_actionAnalyzerChartType {
  none = '',
  day = 'day',
  isoWeek = 'isoWeek',
  month = 'month',
  year = 'year'
}

export enum Taphold_actionAnalyzerCoordSystem {
  time = 'time',
  aggregate = 'aggregate',
  calendar = 'calendar'
}

export enum Taphold_actionAnalyzerAggregation {
  average = 'average',
  sum = 'sum',
  min = 'min',
  max = 'max',
  first = 'first',
  last = 'last',
  diffFirst = 'diff_first',
  diffLast = 'diff_last'
}

export enum ChartType {
  dynamic = '',
  day = 'day',
  isoWeek = 'isoWeek',
  week = 'week',
  month = 'month',
  year = 'year'
}

export type Period = `${number}${PeriodType}` | PeriodType

export enum PeriodType {
  h = 'h',
  D = 'D',
  W = 'W',
  M = 'M',
  Y = 'Y'
}

export enum TimeFormat {
  LTS = 'LTS',
  LT = 'LT',
  HH_mm_ss = 'HH:mm:ss'
}

export enum Timezone {
  Africa_Abidjan = 'Africa/Abidjan',
  Africa_Accra = 'Africa/Accra',
  Africa_AddisAbaba = 'Africa/Addis_Ababa',
  Africa_Algiers = 'Africa/Algiers',
  Africa_Asmera = 'Africa/Asmera',
  Africa_Bamako = 'Africa/Bamako',
  Africa_Bangui = 'Africa/Bangui',
  Africa_Banjul = 'Africa/Banjul',
  Africa_Bissau = 'Africa/Bissau',
  Africa_Blantyre = 'Africa/Blantyre',
  Africa_Brazzaville = 'Africa/Brazzaville',
  Africa_Bujumbura = 'Africa/Bujumbura',
  Africa_Cairo = 'Africa/Cairo',
  Africa_Casablanca = 'Africa/Casablanca',
  Africa_Ceuta = 'Africa/Ceuta',
  Africa_Conakry = 'Africa/Conakry',
  Africa_Dakar = 'Africa/Dakar',
  Africa_DarEsSalaam = 'Africa/Dar_es_Salaam',
  Africa_Djibouti = 'Africa/Djibouti',
  Africa_Douala = 'Africa/Douala',
  Africa_ElAaiun = 'Africa/El_Aaiun',
  Africa_Freetown = 'Africa/Freetown',
  Africa_Gaborone = 'Africa/Gaborone',
  Africa_Harare = 'Africa/Harare',
  Africa_Johannesburg = 'Africa/Johannesburg',
  Africa_Juba = 'Africa/Juba',
  Africa_Kampala = 'Africa/Kampala',
  Africa_Khartoum = 'Africa/Khartoum',
  Africa_Kigali = 'Africa/Kigali',
  Africa_Kinshasa = 'Africa/Kinshasa',
  Africa_Lagos = 'Africa/Lagos',
  Africa_Libreville = 'Africa/Libreville',
  Africa_Lome = 'Africa/Lome',
  Africa_Luanda = 'Africa/Luanda',
  Africa_Lubumbashi = 'Africa/Lubumbashi',
  Africa_Lusaka = 'Africa/Lusaka',
  Africa_Malabo = 'Africa/Malabo',
  Africa_Maputo = 'Africa/Maputo',
  Africa_Maseru = 'Africa/Maseru',
  Africa_Mbabane = 'Africa/Mbabane',
  Africa_Mogadishu = 'Africa/Mogadishu',
  Africa_Monrovia = 'Africa/Monrovia',
  Africa_Nairobi = 'Africa/Nairobi',
  Africa_Ndjamena = 'Africa/Ndjamena',
  Africa_Niamey = 'Africa/Niamey',
  Africa_Nouakchott = 'Africa/Nouakchott',
  Africa_Ouagadougou = 'Africa/Ouagadougou',
  Africa_PortoNovo = 'Africa/Porto-Novo',
  Africa_SaoTome = 'Africa/Sao_Tome',
  Africa_Tripoli = 'Africa/Tripoli',
  Africa_Tunis = 'Africa/Tunis',
  Africa_Windhoek = 'Africa/Windhoek',
  America_Adak = 'America/Adak',
  America_Anchorage = 'America/Anchorage',
  America_Anguilla = 'America/Anguilla',
  America_Antigua = 'America/Antigua',
  America_Araguaina = 'America/Araguaina',
  America_Argentina_LaRioja = 'America/Argentina/La_Rioja',
  America_Argentina_RioGallegos = 'America/Argentina/Rio_Gallegos',
  America_Argentina_Salta = 'America/Argentina/Salta',
  America_Argentina_SanJuan = 'America/Argentina/San_Juan',
  America_Argentina_SanLuis = 'America/Argentina/San_Luis',
  America_Argentina_Tucuman = 'America/Argentina/Tucuman',
  America_Argentina_Ushuaia = 'America/Argentina/Ushuaia',
  America_Aruba = 'America/Aruba',
  America_Asuncion = 'America/Asuncion',
  America_Bahia = 'America/Bahia',
  America_BahiaBanderas = 'America/Bahia_Banderas',
  America_Barbados = 'America/Barbados',
  America_Belem = 'America/Belem',
  America_Belize = 'America/Belize',
  America_BlancSablon = 'America/Blanc-Sablon',
  America_BoaVista = 'America/Boa_Vista',
  America_Bogota = 'America/Bogota',
  America_Boise = 'America/Boise',
  America_BuenosAires = 'America/Buenos_Aires',
  America_CambridgeBay = 'America/Cambridge_Bay',
  America_CampoGrande = 'America/Campo_Grande',
  America_Cancun = 'America/Cancun',
  America_Caracas = 'America/Caracas',
  America_Catamarca = 'America/Catamarca',
  America_Cayenne = 'America/Cayenne',
  America_Cayman = 'America/Cayman',
  America_Chicago = 'America/Chicago',
  America_Chihuahua = 'America/Chihuahua',
  America_CiudadJuarez = 'America/Ciudad_Juarez',
  America_CoralHarbour = 'America/Coral_Harbour',
  America_Cordoba = 'America/Cordoba',
  America_CostaRica = 'America/Costa_Rica',
  America_Coyhaique = 'America/Coyhaique',
  America_Creston = 'America/Creston',
  America_Cuiaba = 'America/Cuiaba',
  America_Curacao = 'America/Curacao',
  America_Danmarkshavn = 'America/Danmarkshavn',
  America_Dawson = 'America/Dawson',
  America_DawsonCreek = 'America/Dawson_Creek',
  America_Denver = 'America/Denver',
  America_Detroit = 'America/Detroit',
  America_Dominica = 'America/Dominica',
  America_Edmonton = 'America/Edmonton',
  America_Eirunepe = 'America/Eirunepe',
  America_ElSalvador = 'America/El_Salvador',
  America_FortNelson = 'America/Fort_Nelson',
  America_Fortaleza = 'America/Fortaleza',
  America_GlaceBay = 'America/Glace_Bay',
  America_Godthab = 'America/Godthab',
  America_GooseBay = 'America/Goose_Bay',
  America_GrandTurk = 'America/Grand_Turk',
  America_Grenada = 'America/Grenada',
  America_Guadeloupe = 'America/Guadeloupe',
  America_Guatemala = 'America/Guatemala',
  America_Guayaquil = 'America/Guayaquil',
  America_Guyana = 'America/Guyana',
  America_Halifax = 'America/Halifax',
  America_Havana = 'America/Havana',
  America_Hermosillo = 'America/Hermosillo',
  America_Indiana_Knox = 'America/Indiana/Knox',
  America_Indiana_Marengo = 'America/Indiana/Marengo',
  America_Indiana_Petersburg = 'America/Indiana/Petersburg',
  America_Indiana_TellCity = 'America/Indiana/Tell_City',
  America_Indiana_Vevay = 'America/Indiana/Vevay',
  America_Indiana_Vincennes = 'America/Indiana/Vincennes',
  America_Indiana_Winamac = 'America/Indiana/Winamac',
  America_Indianapolis = 'America/Indianapolis',
  America_Inuvik = 'America/Inuvik',
  America_Iqaluit = 'America/Iqaluit',
  America_Jamaica = 'America/Jamaica',
  America_Jujuy = 'America/Jujuy',
  America_Juneau = 'America/Juneau',
  America_Kentucky_Monticello = 'America/Kentucky/Monticello',
  America_Kralendijk = 'America/Kralendijk',
  America_LaPaz = 'America/La_Paz',
  America_Lima = 'America/Lima',
  America_LosAngeles = 'America/Los_Angeles',
  America_Louisville = 'America/Louisville',
  America_LowerPrinces = 'America/Lower_Princes',
  America_Maceio = 'America/Maceio',
  America_Managua = 'America/Managua',
  America_Manaus = 'America/Manaus',
  America_Marigot = 'America/Marigot',
  America_Martinique = 'America/Martinique',
  America_Matamoros = 'America/Matamoros',
  America_Mazatlan = 'America/Mazatlan',
  America_Mendoza = 'America/Mendoza',
  America_Menominee = 'America/Menominee',
  America_Merida = 'America/Merida',
  America_Metlakatla = 'America/Metlakatla',
  America_MexicoCity = 'America/Mexico_City',
  America_Miquelon = 'America/Miquelon',
  America_Moncton = 'America/Moncton',
  America_Monterrey = 'America/Monterrey',
  America_Montevideo = 'America/Montevideo',
  America_Montserrat = 'America/Montserrat',
  America_Nassau = 'America/Nassau',
  America_NewYork = 'America/New_York',
  America_Nome = 'America/Nome',
  America_Noronha = 'America/Noronha',
  America_NorthDakota_Beulah = 'America/North_Dakota/Beulah',
  America_NorthDakota_Center = 'America/North_Dakota/Center',
  America_NorthDakota_NewSalem = 'America/North_Dakota/New_Salem',
  America_Ojinaga = 'America/Ojinaga',
  America_Panama = 'America/Panama',
  America_Paramaribo = 'America/Paramaribo',
  America_Phoenix = 'America/Phoenix',
  America_PortAuPrince = 'America/Port-au-Prince',
  America_PortOfSpain = 'America/Port_of_Spain',
  America_PortoVelho = 'America/Porto_Velho',
  America_PuertoRico = 'America/Puerto_Rico',
  America_PuntaArenas = 'America/Punta_Arenas',
  America_RankinInlet = 'America/Rankin_Inlet',
  America_Recife = 'America/Recife',
  America_Regina = 'America/Regina',
  America_Resolute = 'America/Resolute',
  America_RioBranco = 'America/Rio_Branco',
  America_Santarem = 'America/Santarem',
  America_Santiago = 'America/Santiago',
  America_SantoDomingo = 'America/Santo_Domingo',
  America_SaoPaulo = 'America/Sao_Paulo',
  America_Scoresbysund = 'America/Scoresbysund',
  America_Sitka = 'America/Sitka',
  America_StBarthelemy = 'America/St_Barthelemy',
  America_StJohns = 'America/St_Johns',
  America_StKitts = 'America/St_Kitts',
  America_StLucia = 'America/St_Lucia',
  America_StThomas = 'America/St_Thomas',
  America_StVincent = 'America/St_Vincent',
  America_SwiftCurrent = 'America/Swift_Current',
  America_Tegucigalpa = 'America/Tegucigalpa',
  America_Thule = 'America/Thule',
  America_Tijuana = 'America/Tijuana',
  America_Toronto = 'America/Toronto',
  America_Tortola = 'America/Tortola',
  America_Vancouver = 'America/Vancouver',
  America_Whitehorse = 'America/Whitehorse',
  America_Winnipeg = 'America/Winnipeg',
  America_Yakutat = 'America/Yakutat',
  Antarctica_Casey = 'Antarctica/Casey',
  Antarctica_Davis = 'Antarctica/Davis',
  Antarctica_DumontDUrville = 'Antarctica/DumontDUrville',
  Antarctica_Macquarie = 'Antarctica/Macquarie',
  Antarctica_Mawson = 'Antarctica/Mawson',
  Antarctica_McMurdo = 'Antarctica/McMurdo',
  Antarctica_Palmer = 'Antarctica/Palmer',
  Antarctica_Rothera = 'Antarctica/Rothera',
  Antarctica_Syowa = 'Antarctica/Syowa',
  Antarctica_Troll = 'Antarctica/Troll',
  Antarctica_Vostok = 'Antarctica/Vostok',
  Arctic_Longyearbyen = 'Arctic/Longyearbyen',
  Asia_Aden = 'Asia/Aden',
  Asia_Almaty = 'Asia/Almaty',
  Asia_Amman = 'Asia/Amman',
  Asia_Anadyr = 'Asia/Anadyr',
  Asia_Aqtau = 'Asia/Aqtau',
  Asia_Aqtobe = 'Asia/Aqtobe',
  Asia_Ashgabat = 'Asia/Ashgabat',
  Asia_Atyrau = 'Asia/Atyrau',
  Asia_Baghdad = 'Asia/Baghdad',
  Asia_Bahrain = 'Asia/Bahrain',
  Asia_Baku = 'Asia/Baku',
  Asia_Bangkok = 'Asia/Bangkok',
  Asia_Barnaul = 'Asia/Barnaul',
  Asia_Beirut = 'Asia/Beirut',
  Asia_Bishkek = 'Asia/Bishkek',
  Asia_Brunei = 'Asia/Brunei',
  Asia_Calcutta = 'Asia/Calcutta',
  Asia_Chita = 'Asia/Chita',
  Asia_Colombo = 'Asia/Colombo',
  Asia_Damascus = 'Asia/Damascus',
  Asia_Dhaka = 'Asia/Dhaka',
  Asia_Dili = 'Asia/Dili',
  Asia_Dubai = 'Asia/Dubai',
  Asia_Dushanbe = 'Asia/Dushanbe',
  Asia_Famagusta = 'Asia/Famagusta',
  Asia_Gaza = 'Asia/Gaza',
  Asia_Hebron = 'Asia/Hebron',
  Asia_HongKong = 'Asia/Hong_Kong',
  Asia_Hovd = 'Asia/Hovd',
  Asia_Irkutsk = 'Asia/Irkutsk',
  Asia_Jakarta = 'Asia/Jakarta',
  Asia_Jayapura = 'Asia/Jayapura',
  Asia_Jerusalem = 'Asia/Jerusalem',
  Asia_Kabul = 'Asia/Kabul',
  Asia_Kamchatka = 'Asia/Kamchatka',
  Asia_Karachi = 'Asia/Karachi',
  Asia_Katmandu = 'Asia/Katmandu',
  Asia_Khandyga = 'Asia/Khandyga',
  Asia_Krasnoyarsk = 'Asia/Krasnoyarsk',
  Asia_KualaLumpur = 'Asia/Kuala_Lumpur',
  Asia_Kuching = 'Asia/Kuching',
  Asia_Kuwait = 'Asia/Kuwait',
  Asia_Macau = 'Asia/Macau',
  Asia_Magadan = 'Asia/Magadan',
  Asia_Makassar = 'Asia/Makassar',
  Asia_Manila = 'Asia/Manila',
  Asia_Muscat = 'Asia/Muscat',
  Asia_Nicosia = 'Asia/Nicosia',
  Asia_Novokuznetsk = 'Asia/Novokuznetsk',
  Asia_Novosibirsk = 'Asia/Novosibirsk',
  Asia_Omsk = 'Asia/Omsk',
  Asia_Oral = 'Asia/Oral',
  Asia_PhnomPenh = 'Asia/Phnom_Penh',
  Asia_Pontianak = 'Asia/Pontianak',
  Asia_Pyongyang = 'Asia/Pyongyang',
  Asia_Qatar = 'Asia/Qatar',
  Asia_Qostanay = 'Asia/Qostanay',
  Asia_Qyzylorda = 'Asia/Qyzylorda',
  Asia_Rangoon = 'Asia/Rangoon',
  Asia_Riyadh = 'Asia/Riyadh',
  Asia_Saigon = 'Asia/Saigon',
  Asia_Sakhalin = 'Asia/Sakhalin',
  Asia_Samarkand = 'Asia/Samarkand',
  Asia_Seoul = 'Asia/Seoul',
  Asia_Shanghai = 'Asia/Shanghai',
  Asia_Singapore = 'Asia/Singapore',
  Asia_Srednekolymsk = 'Asia/Srednekolymsk',
  Asia_Taipei = 'Asia/Taipei',
  Asia_Tashkent = 'Asia/Tashkent',
  Asia_Tbilisi = 'Asia/Tbilisi',
  Asia_Tehran = 'Asia/Tehran',
  Asia_Thimphu = 'Asia/Thimphu',
  Asia_Tokyo = 'Asia/Tokyo',
  Asia_Tomsk = 'Asia/Tomsk',
  Asia_Ulaanbaatar = 'Asia/Ulaanbaatar',
  Asia_Urumqi = 'Asia/Urumqi',
  Asia_UstNera = 'Asia/Ust-Nera',
  Asia_Vientiane = 'Asia/Vientiane',
  Asia_Vladivostok = 'Asia/Vladivostok',
  Asia_Yakutsk = 'Asia/Yakutsk',
  Asia_Yekaterinburg = 'Asia/Yekaterinburg',
  Asia_Yerevan = 'Asia/Yerevan',
  Atlantic_Azores = 'Atlantic/Azores',
  Atlantic_Bermuda = 'Atlantic/Bermuda',
  Atlantic_Canary = 'Atlantic/Canary',
  Atlantic_CapeVerde = 'Atlantic/Cape_Verde',
  Atlantic_Faeroe = 'Atlantic/Faeroe',
  Atlantic_Madeira = 'Atlantic/Madeira',
  Atlantic_Reykjavik = 'Atlantic/Reykjavik',
  Atlantic_SouthGeorgia = 'Atlantic/South_Georgia',
  Atlantic_StHelena = 'Atlantic/St_Helena',
  Atlantic_Stanley = 'Atlantic/Stanley',
  Australia_Adelaide = 'Australia/Adelaide',
  Australia_Brisbane = 'Australia/Brisbane',
  Australia_BrokenHill = 'Australia/Broken_Hill',
  Australia_Darwin = 'Australia/Darwin',
  Australia_Eucla = 'Australia/Eucla',
  Australia_Hobart = 'Australia/Hobart',
  Australia_Lindeman = 'Australia/Lindeman',
  Australia_LordHowe = 'Australia/Lord_Howe',
  Australia_Melbourne = 'Australia/Melbourne',
  Australia_Perth = 'Australia/Perth',
  Australia_Sydney = 'Australia/Sydney',
  Europe_Amsterdam = 'Europe/Amsterdam',
  Europe_Andorra = 'Europe/Andorra',
  Europe_Astrakhan = 'Europe/Astrakhan',
  Europe_Athens = 'Europe/Athens',
  Europe_Belgrade = 'Europe/Belgrade',
  Europe_Berlin = 'Europe/Berlin',
  Europe_Bratislava = 'Europe/Bratislava',
  Europe_Brussels = 'Europe/Brussels',
  Europe_Bucharest = 'Europe/Bucharest',
  Europe_Budapest = 'Europe/Budapest',
  Europe_Busingen = 'Europe/Busingen',
  Europe_Chisinau = 'Europe/Chisinau',
  Europe_Copenhagen = 'Europe/Copenhagen',
  Europe_Dublin = 'Europe/Dublin',
  Europe_Gibraltar = 'Europe/Gibraltar',
  Europe_Guernsey = 'Europe/Guernsey',
  Europe_Helsinki = 'Europe/Helsinki',
  Europe_IsleOfMan = 'Europe/Isle_of_Man',
  Europe_Istanbul = 'Europe/Istanbul',
  Europe_Jersey = 'Europe/Jersey',
  Europe_Kaliningrad = 'Europe/Kaliningrad',
  Europe_Kiev = 'Europe/Kiev',
  Europe_Kirov = 'Europe/Kirov',
  Europe_Lisbon = 'Europe/Lisbon',
  Europe_Ljubljana = 'Europe/Ljubljana',
  Europe_London = 'Europe/London',
  Europe_Luxembourg = 'Europe/Luxembourg',
  Europe_Madrid = 'Europe/Madrid',
  Europe_Malta = 'Europe/Malta',
  Europe_Mariehamn = 'Europe/Mariehamn',
  Europe_Minsk = 'Europe/Minsk',
  Europe_Monaco = 'Europe/Monaco',
  Europe_Moscow = 'Europe/Moscow',
  Europe_Oslo = 'Europe/Oslo',
  Europe_Paris = 'Europe/Paris',
  Europe_Podgorica = 'Europe/Podgorica',
  Europe_Prague = 'Europe/Prague',
  Europe_Riga = 'Europe/Riga',
  Europe_Rome = 'Europe/Rome',
  Europe_Samara = 'Europe/Samara',
  Europe_SanMarino = 'Europe/San_Marino',
  Europe_Sarajevo = 'Europe/Sarajevo',
  Europe_Saratov = 'Europe/Saratov',
  Europe_Simferopol = 'Europe/Simferopol',
  Europe_Skopje = 'Europe/Skopje',
  Europe_Sofia = 'Europe/Sofia',
  Europe_Stockholm = 'Europe/Stockholm',
  Europe_Tallinn = 'Europe/Tallinn',
  Europe_Tirane = 'Europe/Tirane',
  Europe_Ulyanovsk = 'Europe/Ulyanovsk',
  Europe_Vaduz = 'Europe/Vaduz',
  Europe_Vatican = 'Europe/Vatican',
  Europe_Vienna = 'Europe/Vienna',
  Europe_Vilnius = 'Europe/Vilnius',
  Europe_Volgograd = 'Europe/Volgograd',
  Europe_Warsaw = 'Europe/Warsaw',
  Europe_Zagreb = 'Europe/Zagreb',
  Europe_Zurich = 'Europe/Zurich',
  Indian_Antananarivo = 'Indian/Antananarivo',
  Indian_Chagos = 'Indian/Chagos',
  Indian_Christmas = 'Indian/Christmas',
  Indian_Cocos = 'Indian/Cocos',
  Indian_Comoro = 'Indian/Comoro',
  Indian_Kerguelen = 'Indian/Kerguelen',
  Indian_Mahe = 'Indian/Mahe',
  Indian_Maldives = 'Indian/Maldives',
  Indian_Mauritius = 'Indian/Mauritius',
  Indian_Mayotte = 'Indian/Mayotte',
  Indian_Reunion = 'Indian/Reunion',
  Pacific_Apia = 'Pacific/Apia',
  Pacific_Auckland = 'Pacific/Auckland',
  Pacific_Bougainville = 'Pacific/Bougainville',
  Pacific_Chatham = 'Pacific/Chatham',
  Pacific_Easter = 'Pacific/Easter',
  Pacific_Efate = 'Pacific/Efate',
  Pacific_Enderbury = 'Pacific/Enderbury',
  Pacific_Fakaofo = 'Pacific/Fakaofo',
  Pacific_Fiji = 'Pacific/Fiji',
  Pacific_Funafuti = 'Pacific/Funafuti',
  Pacific_Galapagos = 'Pacific/Galapagos',
  Pacific_Gambier = 'Pacific/Gambier',
  Pacific_Guadalcanal = 'Pacific/Guadalcanal',
  Pacific_Guam = 'Pacific/Guam',
  Pacific_Honolulu = 'Pacific/Honolulu',
  Pacific_Kiritimati = 'Pacific/Kiritimati',
  Pacific_Kosrae = 'Pacific/Kosrae',
  Pacific_Kwajalein = 'Pacific/Kwajalein',
  Pacific_Majuro = 'Pacific/Majuro',
  Pacific_Marquesas = 'Pacific/Marquesas',
  Pacific_Midway = 'Pacific/Midway',
  Pacific_Nauru = 'Pacific/Nauru',
  Pacific_Niue = 'Pacific/Niue',
  Pacific_Norfolk = 'Pacific/Norfolk',
  Pacific_Noumea = 'Pacific/Noumea',
  Pacific_PagoPago = 'Pacific/Pago_Pago',
  Pacific_Palau = 'Pacific/Palau',
  Pacific_Pitcairn = 'Pacific/Pitcairn',
  Pacific_Ponape = 'Pacific/Ponape',
  Pacific_PortMoresby = 'Pacific/Port_Moresby',
  Pacific_Rarotonga = 'Pacific/Rarotonga',
  Pacific_Saipan = 'Pacific/Saipan',
  Pacific_Tahiti = 'Pacific/Tahiti',
  Pacific_Tarawa = 'Pacific/Tarawa',
  Pacific_Tongatapu = 'Pacific/Tongatapu',
  Pacific_Truk = 'Pacific/Truk',
  Pacific_Wake = 'Pacific/Wake',
  Pacific_Wallis = 'Pacific/Wallis'
}

export enum DateFormat {
  LL = 'LL',
  L = 'L',
  MM_DD_YYYY = 'MM/DD/YYYY'
}

export enum Modules {
  wheel = 'wheel',
  sbSpectrum = 'sb-spectrum',
  hueSlider = 'hue-slider',
  hsSpectrum = 'hs-spectrum',
  brightnessSlider = 'brightness-slider',
  rgbSliders = 'rgb-sliders',
  hsbSliders = 'hsb-sliders',
  rgbBars = 'rgb-bars',
  palette = 'palette',
  currentColor = 'current-color',
  initialCurrentColors = 'initial-current-colors'
}

export enum GaugeType {
  circle = 'circle',
  semicircle = 'semicircle'
}

export enum CircleShape {
  full = 'full',
  halfTop = 'half-top',
  halfBottom = 'half-bottom',
  halfLeft = 'half-left',
  halfRight = 'half-right',
  quarterTopLeft = 'quarter-top-left',
  quarterTopRight = 'quarter-top-right',
  quarterBottomLeft = 'quarter-bottom-left',
  quarterBottomRight = 'quarter-bottom-right',
  pie = 'pie'
}

export enum LineCap {
  square = 'square',
  round = 'round'
}

export enum HandleShape {
  square = 'square',
  round = 'round',
  dot = 'dot'
}

export enum DirIconsStyle {
  arrowtriangle__dir_ = 'arrowtriangle_{dir}',
  arrowtriangle__dir_Fill = 'arrowtriangle_{dir}_fill',
  arrowtriangle__dir_Circle = 'arrowtriangle_{dir}_circle',
  arrowtriangle__dir_CircleFill = 'arrowtriangle_{dir}_circle_fill',
  arrowtriangle__dir_Square = 'arrowtriangle_{dir}_square',
  arrowtriangle__dir_SquareFill = 'arrowtriangle_{dir}_square_fill',
  chevron__dir_ = 'chevron_{dir}',
  chevron__dir_2 = 'chevron_{dir}_2',
  chevronCompact__dir_2 = 'chevron_compact_{dir}_2',
  chevron__dir_Fill = 'chevron_{dir}_fill',
  chevron__dir_Circle = 'chevron_{dir}_circle',
  chevron__dir_CircleFill = 'chevron_{dir}_circle_fill',
  chevron__dir_Square = 'chevron_{dir}_square',
  chevron__dir_SquareFill = 'chevron_{dir}_square_fill',
  arrow__dir_ = 'arrow_{dir}',
  arrow__dir_2 = 'arrow_{dir}_2',
  arrow__dir_Fill = 'arrow_{dir}_fill',
  arrow__dir_Circle = 'arrow_{dir}_circle',
  arrow__dir_CircleFill = 'arrow_{dir}_circle_fill',
  arrow__dir_Square = 'arrow_{dir}_square',
  arrow__dir_SquareFill = 'arrow_{dir}_square_fill',
  arrow__dir_ToLine = 'arrow_{dir}_to_line',
  arrow__dir_ToLineAlt = 'arrow_{dir}_to_line_alt'
}

export enum StopIconStyle {
  stop = 'stop',
  stopFill = 'stop_fill',
  stopCircle = 'stop_circle',
  stopCircleFill = 'stop_circle_fill',
  multiply = 'multiply',
  multiplyFill = 'multiply_fill',
  multiplyCircle = 'multiply_circle',
  multiplyCircleFill = 'multiply_circle_fill'
}

export enum TrendGradientDirection {
  top = 'top',
  bottom = 'bottom',
  left = 'left',
  right = 'right'
}

export enum PlayerType {
  videojs = 'videojs',
  webrtc = 'webrtc'
}

export enum NameLocation {
  start = 'start',
  center = 'center',
  end = 'end'
}

export enum Orient {
  horizontal = 'horizontal',
  vertical = 'vertical'
}

export enum OffsetUnit {
  hour = 'hour',
  minute = 'minute',
  day = 'day',
  week = 'week',
  month = 'month',
  year = 'year'
}

export enum Type {
  line = 'line',
  bar = 'bar',
  heatmap = 'heatmap',
  scatter = 'scatter'
}

export enum AggregationFunction {
  average = 'average',
  sum = 'sum',
  min = 'min',
  max = 'max',
  first = 'first',
  last = 'last',
  diffFirst = 'diff_first',
  diffLast = 'diff_last'
}

export enum BackgroundColor {
  red = 'red',
  green = 'green',
  blue = 'blue',
  pink = 'pink',
  yellow = 'yellow',
  orange = 'orange',
  purple = 'purple',
  deeppurple = 'deeppurple',
  lightblue = 'lightblue',
  teal = 'teal',
  lime = 'lime',
  deeporange = 'deeporange',
  gray = 'gray',
  black = 'black'
}

export enum Item {

}

