<template>
  <f7-block class="help-sidebar">
    <f7-navbar style="width: 100%" title="Help" :color="$f7.data.themeOptions.dark === 'dark' ? '' : 'black'" />
    <div class="help-sidebar-content">
      <f7-segmented strong tag="p" style="margin-right: calc(var(--f7-searchbar-inner-padding-right) + var(--f7-safe-area-right)); margin-left: calc(var(--f7-searchbar-inner-padding-left) + var(--f7-safe-area-left))">
        <f7-button :active="activeHelpTab === 'quick'" icon-f7="cursor_rays" icon-size="18" @click="activeHelpTab = 'quick'" />
        <f7-button :active="activeHelpTab === 'faq'" icon-f7="question_diamond_fill" icon-size="18" @click="activeHelpTab = 'faq'" />
        <f7-button :active="activeHelpTab === 'glossary'" icon-f7="square_favorites_fill" icon-size="18" @click="activeHelpTab = 'glossary'" />
        <f7-button :active="activeHelpTab === 'more'" icon-f7="text_bubble_fill" icon-size="18" @click="activeHelpTab = 'more'" />
      </f7-segmented>
      <div v-if="activeHelpTab === 'quick'">
        <f7-block class="no-margin no-padding">
          <f7-block-title class="padding-horizontal" medium>
            Quick Start
          </f7-block-title>
        </f7-block>
        <f7-block class="no-margin no-padding">
          <f7-list>
            <f7-list-item link="/settings/addons" title="1. Install a Binding"></f7-list-item>
            <f7-list-item link="/settings/things/inbox" title="2. Add a Thing"></f7-list-item>
            <f7-list-item link="/settings/things" title="3. Configure the Thing"></f7-list-item>
            <f7-list-item link="/settings/items" title="4. Create an Item"></f7-list-item>
            <f7-list-item link="/settings/pages" title="5. Display Item in UI"></f7-list-item>
          </f7-list>
        </f7-block>
        <f7-block class="no-margin no-padding">
          <f7-block-title class="padding-horizontal" medium>
            Semantic Model
          </f7-block-title>
        </f7-block>
        <f7-block class="no-margin no-padding">
          <f7-list>
            <f7-list-item link="addons/" title="1. Create Base Location"></f7-list-item>
            <f7-list-item link="things/inbox/" title="2. Add Additional Locations"></f7-list-item>
            <f7-list-item link="things/" title="3. Add Equipment"></f7-list-item>
            <f7-list-item link="pages/" title="4. View Autogenerated Model Cards"></f7-list-item>
          </f7-list>
        </f7-block>
      </div>

      <div v-else-if="activeHelpTab === 'faq'">
        <f7-block class="no-margin no-padding">
          <f7-block-title class="padding-horizontal display-flex" medium>
            <span>How do I...</span>
          </f7-block-title>
        </f7-block>
        <f7-block class="no-margin no-padding">
          <f7-list accordion-list>
            <f7-list-item accordion-item title="Create a rule?">
              <f7-accordion-content>
                <f7-block>
                  <p>
                    In the left panel go to <f7-link href="rules/">Settings -> Rules</f7-link> and then click on the blue plus in the lower right corner.
                  </p>
                  <p><f7-link external target="_blank" href="https://www.openhab.org/docs/tutorial/rules_introduction.html">Full Help Docs</f7-link></p>
                </f7-block>
              </f7-accordion-content>
            </f7-list-item>
            <f7-list-item accordion-item title="Delete an Item?">
              <f7-accordion-content>
                <f7-block>
                  <p>
                    Lorem Ipsum
                  </p>
                </f7-block>
              </f7-accordion-content>
            </f7-list-item>
            <f7-list-item accordion-item title="Do this other thing?">
              <f7-accordion-content>
                <f7-block>
                  <p>
                    Lorem Ipsum
                  </p>
                </f7-block>
              </f7-accordion-content>
            </f7-list-item>
          </f7-list>
        </f7-block>
      </div>

      <div v-else-if="activeHelpTab === 'glossary'">
        <f7-block class="no-margin no-padding">
          <f7-block-title class="padding-horizontal" medium>
            Glossary
          </f7-block-title>
        </f7-block>
        <f7-block class="no-margin no-padding">
          <f7-list accordion-list>
            <f7-list-item accordion-item title="Binding">
              <f7-accordion-content>
                <f7-block>
                  <p>
                    An add-on to openHAB that allows some 3rd party service or device(s) to communicate with the core software.
                  </p>
                </f7-block>
              </f7-accordion-content>
            </f7-list-item>
            <f7-list-item accordion-item title="Channel">
              <f7-accordion-content>
                <f7-block>
                  <p>
                    One single attribute of a Thing which openHAB can read and/or write
                  </p>
                </f7-block>
              </f7-accordion-content>
            </f7-list-item>
            <f7-list-item accordion-item title="Event">
              <f7-accordion-content>
                <f7-block>
                  <p>
                    An occurrence such as a change in Item State or the triggering of a Channel with the potential to trigger a reaction. See events.log.
                  </p>
                </f7-block>
              </f7-accordion-content>
            </f7-list-item>
          </f7-list>
        </f7-block>
      </div>

      <div v-else-if="activeHelpTab === 'more'">
        <f7-block class="no-margin no-padding">
          <f7-block-title class="padding-horizontal" medium>
            More Resources
          </f7-block-title>
        </f7-block>
        <f7-block>
          <p><f7-link external target="_blank" href="https://www.openhab.org/" v-t="'about.homePage'" /></p>
          <p><f7-link external target="_blank" href="https://www.openhab.org/docs/" v-t="'about.documentation'" /></p>
          <p><f7-link external target="_blank" href="https://community.openhab.org/" v-t="'about.communityForum'" /></p>
        </f7-block>
      </div>
    </div>

  </f7-block>
</template>

<style lang="stylus">
.panel-right.panel-in-breakpoint:before
  position absolute
  left 0
  top 0
  height 100%
  width 1px
  background rgba(0,0,0,0.1)
  content ''
  z-index 6000

.help-sidebar
  scrollbar-width none /* Firefox */
  -ms-overflow-style none  /* IE 10+ */
  margin 0
  padding 0
  width 100%

  .help-sidebar-content
    padding-top 0.3rem

  &.page
    background #e7e7e7 !important

  .page-content
    overflow-x hidden
.md .help-sidebar-content
  margin-top 0
.theme-dark
  .help-sidebar
    &.page
      background #232323 !important
</style>

<script>

export default {
  data () {
    return {
      activeHelpTab: 'quick'
    }
  }
}
</script>
