name: RelativeCI

on:
  workflow_run:
    workflows: ["Main UI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # pinning to SHA to mitigate possible supply chain attack
      - name: Send bundle stats and build information to RelativeCI
        uses: relative-ci/agent-action@fcf45416581928e8dd62eded78ce98c78e5149f8 # v3.2.3
        with:
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
