<template>
  <f7-page @page:afterin="onPageAfterIn" @page:beforeout="onPageBeforeOut">
    <f7-navbar :title="newTransformation ? 'Create Transformation' : 'Edit Transformation'" :subtitle="(!newTransformation && transformation && transformation.configuration) ? transformation.configuration.mode : ''" back-link="Back">
      <f7-nav-right v-if="isEditable && !newTransformation">
        <f7-link @click="save()" v-if="$theme.md" icon-md="material:save" icon-only />
        <f7-link @click="save()" v-if="!$theme.md">
          Save<span v-if="$device.desktop">&nbsp;(Ctrl-S)</span>
        </f7-link>
      </f7-nav-right>
      <f7-nav-right v-else-if="isEditable && newTransformation">
        <f7-link @click="createTransformation" v-if="$theme.md && newTransformation" icon-md="material:save" icon-only />
        <f7-link @click="createTransformation" v-if="$theme.ios && newTransformation">
          Create
        </f7-link>
      </f7-nav-right>
    </f7-navbar>
    <!-- Create Transformation -->
    <transformation-general-settings v-if="newTransformation && ready" :createMode="true" :transformation="transformation" :types="types" :languages="languages" :language="language" :scriptLanguages="scriptLanguages" @newLanguage="language = $event" @newType="transformation.type = $event" @newScriptMimeType="transformation.configuration.mode = $event" />
    <div v-if="ready && newTransformation" class="if-aurora display-flex justify-content-center margin padding">
      <div class="flex-shrink-0">
        <f7-button class="padding-left padding-right" style="width: 150px" color="blue" large raised fill @click="createTransformation">
          Create
        </f7-button>
      </div>
    </div>
    <!-- Edit Transformation -->
    <f7-toolbar v-if="!newTransformation && ready" position="bottom">
      <span class="display-flex flex-direction-row align-items-center" />
      <span class="display-flex flex-direction-row align-items-center">
        <f7-segmented v-if="isBlockly" class="margin-right">
          <f7-button outline small :active="!blocklyCodePreview" icon-f7="ticket" :icon-size="($theme.aurora) ? 20 : 22" class="no-ripple" @click="blocklyCodePreview = false" />
          <f7-button outline small :active="blocklyCodePreview" icon-f7="doc_text" :icon-size="($theme.aurora) ? 20 : 22" class="no-ripple" @click="showBlocklyCode" />
        </f7-segmented>
        <f7-link class="right details-link padding-right" ref="detailsLink" @click="detailsOpened = true" icon-f7="chevron_up" />
      </span>
    </f7-toolbar>
    <f7-icon v-if="!newTransformation && ready && (!isBlockly && !isEditable) || (blocklyCodePreview && isBlockly)" f7="lock" class="float-right margin" style="opacity:0.5; z-index: 4000; user-select: none;" size="50" color="gray"
             :tooltip="(isBlockly) ? 'Cannot edit the code generated by Blockly' : 'This rule is not editable because it has been provisioned from a file'" />
    <editor v-if="!newTransformation && ready && (!isBlockly || blocklyCodePreview)" class="rule-script-editor" :mode="transformation.configuration.mode || ''" :value="transformation.configuration.function" @input="onEditorInput" :read-only="isBlockly || !isEditable" :tern-autocompletion-hook="true" />
    <blockly-editor ref="blocklyEditor" v-else-if="isBlockly" :blocks="transformation.configuration.blockSource" @change="dirty = true" />
    <!-- TODO: Enable Blockly after blocks have been adjusted
    <f7-fab v-show="transformation.configuration && !transformation.configuration.function && transformation.configuration.mode === 'application/javascript' && !isBlockly" position="center-bottom" slot="fixed" color="blue" @click="convertToBlockly" text="Design with Blockly">
      <f7-icon f7="ticket_fill" />
    </f7-fab>
    -->

    <f7-sheet ref="detailsSheet" class="transformation-details-sheet" :backdrop="false" :close-on-escape="true" :opened="detailsOpened" @sheet:closed="detailsOpened = false">
      <f7-page>
        <f7-toolbar tabbar bottom>
          <span class="margin-left">Transformation details</span>
          <div class="right">
            <f7-link sheet-close class="padding-right">
              <f7-icon f7="chevron_down" />
            </f7-link>
          </div>
        </f7-toolbar>
        <f7-block class="block-narrow">
          <transformation-general-settings :createMode="newTransformation" :transformation="transformation" />
          <f7-col v-if="isEditable">
            <f7-list>
              <f7-list-button color="red" @click="deleteTransformation">
                Remove Transformation
              </f7-list-button>
            </f7-list>
          </f7-col>
        </f7-block>
      </f7-page>
    </f7-sheet>
  </f7-page>
</template>

<style lang="stylus">
.transformation-editor.vue-codemirror
  display block
  top calc(var(--f7-navbar-height) + var(--f7-tabbar-height))
  height calc(100% - 2*var(--f7-navbar-height))
  width 100%
</style>

<script>
import DirtyMixin from '../dirty-mixin'
import TransformationGeneralSettings from '@/pages/settings/transformations/transformation-general-settings'

export default {
  mixins: [DirtyMixin],
  components: {
    TransformationGeneralSettings,
    'editor': () => import(/* webpackChunkName: "script-editor" */ '@/components/config/controls/script-editor.vue'),
    'blockly-editor': () => import(/* webpackChunkName: "blockly-editor" */ '@/components/config/controls/blockly-editor.vue')
  },
  props: ['transformationId', 'createMode'],
  data () {
    return {
      newTransformation: this.createMode,
      ready: false,
      loading: false,
      transformation: {},
      types: [],
      scriptLanguages: [],
      languages: [],
      language: '',
      detailsOpened: false,
      blocklyCodePreview: false
    }
  },
  computed: {
    isEditable () {
      return this.transformation && this.transformation.editable !== false
    },
    isBlockly () {
      // TODO: Enable Blockly after blocks have been adjusted
      // return this.transformation.configuration && this.transformation.configuration.blockSource
      return false
    }
  },
  methods: {
    onPageAfterIn () {
      if (this.ready) return
      if (this.newTransformation) {
        this.initializeNewTransformation()
        return
      }
      if (window) {
        window.addEventListener('keydown', this.keyDown)
      }
      this.load()
    },
    onPageBeforeOut () {
      if (this.$refs.detailsSheet.f7Sheet) this.$refs.detailsSheet.f7Sheet.close()
      if (window) {
        window.removeEventListener('keydown', this.keyDown)
      }
    },
    initializeNewTransformation () {
      this.transformation = {
        uid: this.$f7.utils.id(),
        label: '',
        type: '',
        configuration: {
          function: '',
          mode: ''
        },
        editable: true
      }
      Promise.all([this.$oh.api.get('/rest/transformations/services'), this.$oh.api.get('/rest/module-types/script.ScriptAction'), this.$oh.api.get('/rest/config-descriptions/system:i18n')]).then((data) => {
        this.$set(this, 'types', data[0])

        this.$set(this, 'scriptLanguages', data[1].configDescriptions
          .find((c) => c.name === 'type').options
          .map((l) => {
            return {
              contentType: l.value,
              name: l.label.split(' (')[0],
              version: l.label.split(' (')[1].replace(')', '')
            }
          }))

        this.$set(this, 'languages', data[2].parameters.find(p => p.name === 'language').options)
      })
      this.language = ''
      this.ready = true
    },
    createTransformation () {
      if (!this.transformation.uid) {
        this.$f7.dialog.alert('Please give an ID to the configuration')
        return
      }
      if (!this.transformation.type) {
        this.$f7.dialog.alert('Please give the type of the transformation')
        return
      }
      if (!this.transformation.label) {
        this.$f7.dialog.alert('Please give a label for this transformation')
        return
      }

      this.transformation.uid = 'config:' + this.transformation.type + ':' + this.transformation.uid

      if (this.language) {
        this.transformation.uid += ':' + this.language
      }

      this.$oh.api.put('/rest/transformations/' + this.transformation.uid, this.transformation).then(() => {
        this.$f7.toast.create({
          text: 'Transformation created',
          destroyOnClose: true,
          closeTimeout: 2000
        }).open()
        this.$f7router.navigate(this.$f7route.url.replace('/add', '/' + this.transformation.uid), { reloadCurrent: true })
        this.newTransformation = false
        this.ready = false
        if (window) {
          window.addEventListener('keydown', this.keyDown)
        }
        this.load()
      })
    },
    load () {
      if (this.loading) return
      this.loading = true

      this.$oh.api.get('/rest/transformations/' + this.transformationId).then((data) => {
        this.$set(this, 'transformation', data)
        this.loading = false
        this.ready = true
      })
    },
    save (noToast) {
      if (!this.isEditable) return
      if (this.isBlockly) {
        try {
          this.transformation.configuration.blockSource = this.$refs.blocklyEditor.getBlocks()
          this.transformation.configuration.function = this.$refs.blocklyEditor.getCode()
        } catch (e) {
          this.$f7.dialog.alert(e)
          return Promise.reject(e)
        }
      }
      return this.$oh.api.put('/rest/transformations/' + this.transformation.uid, this.transformation).then((data) => {
        this.dirty = false
        if (!noToast) {
          this.$f7.toast.create({
            text: 'Transformation updated',
            destroyOnClose: true,
            closeTimeout: 2000
          }).open()
        }
      }).catch((err) => {
        this.$f7.toast.create({
          text: 'Error while saving transformation configuration: ' + err,
          destroyOnClose: true,
          closeTimeout: 2000
        }).open()
      })
    },
    deleteTransformation () {
      this.$f7.dialog.confirm(
        `Are you sure you want to delete ${this.transformation.uid}?`,
        'Delete Transformation',
        () => {
          this.$oh.api.delete('/rest/transformations/' + this.transformation.uid).then(() => {
            this.$f7router.back('/settings/transformations/', { force: true })
          })
        }
      )
    },
    showBlocklyCode () {
      try {
        this.transformation.configuration.blockSource = this.$refs.blocklyEditor.getBlocks()
        this.transformation.configuration.function = this.$refs.blocklyEditor.getCode()
        if (this.isBlockly) this.blocklyCodePreview = true
      } catch (e) {
        this.$f7.dialog.alert(e)
      }
    },
    convertToBlockly () {
      if ((this.configuration && this.transformation.configuration.function) || this.isBlockly || this.transformation.configuration.mode !== 'application/javascript') return
      this.$set(this.transformation.configuration, 'blockSource', '<xml xmlns="https://developers.google.com/blockly/xml"></xml>')
    },
    onEditorInput (value) {
      this.transformation.configuration.function = value
      this.dirty = true
    },
    keyDown (ev) {
      if ((ev.ctrlKey || ev.metaKey) && !(ev.altKey || ev.shiftKey)) {
        switch (ev.keyCode) {
          case 66:
            if (this.isBlockly) {
              if (this.blocklyCodePreview) {
                this.blocklyCodePreview = false
              } else {
                this.showBlocklyCode()
              }
            } else {
              this.convertToBlockly()
            }
            ev.stopPropagation()
            ev.preventDefault()
            break
          case 83:
            this.save()
            ev.stopPropagation()
            ev.preventDefault()
            break
        }
      }
    }
  }
}
</script>
