<template>
  <f7-page @page:afterin="onPageAfterIn" @page:beforeout="onPageBeforeOut">
    <f7-navbar :title="pageTitle" :subtitle="(!newTransformation) ? context.mode : undefined" back-link="Back">
      <f7-nav-right v-if="isEditable && !newTransformation">
        <f7-link @click="save()" v-if="$theme.md" icon-md="material:save" icon-only />
        <f7-link @click="save()" v-if="!$theme.md">
          Save<span v-if="$device.desktop">&nbsp;(Ctrl-S)</span>
        </f7-link>
      </f7-nav-right>
      <f7-nav-right v-else-if="isEditable && newTransformation">
        <f7-link @click="createTransformation" v-if="$theme.md && newTransformation" icon-md="material:save" icon-only />
        <f7-link @click="createTransformation" v-if="$theme.ios && newTransformation">
          Create
        </f7-link>
      </f7-nav-right>
    </f7-navbar>
    <f7-toolbar v-if="!newTransformation && ready" position="bottom">
      <span class="display-flex flex-direction-row align-items-center" />
      <span class="display-flex flex-direction-row align-items-center">
        <f7-segmented v-if="!newTransformation && isBlockly" class="margin-right">
          <f7-button outline small :active="!blocklyCodePreview" icon-f7="ticket" :icon-size="($theme.aurora) ? 20 : 22" class="no-ripple" @click="blocklyCodePreview = false" />
          <f7-button outline small :active="blocklyCodePreview" icon-f7="doc_text" :icon-size="($theme.aurora) ? 20 : 22" class="no-ripple" @click="showBlocklyCode" />
        </f7-segmented>
        <f7-link class="right details-link padding-right" ref="detailsLink" @click="detailsOpened = true" icon-f7="chevron_up" />
      </span>
    </f7-toolbar>
    <f7-icon v-if="ready && !newTransformation && (!isBlockly && !isEditable) || (blocklyCodePreview && isBlockly)" f7="lock" class="float-right margin" style="opacity:0.5; z-index: 4000; user-select: none;" size="50" color="gray"
             :tooltip="(isBlockly) ? 'Cannot edit the code generated by Blockly' : 'This transformation configuration is not editable because it has been provisioned from a file'" />
    <editor v-if="ready && !newTransformation && (!isBlockly || blocklyCodePreview)" class="rule-script-editor" :mode="context.mode" :value="configuration.content" @input="onEditorInput" :read-only="isBlockly || !isEditable" :tern-autocompletion-hook="true" />
    <blockly-editor ref="blocklyEditor" v-else-if="ready && !newTransformation && isBlockly" :blocks="context.blockSource" @change="dirty = true" />
    <transformation-general-settings v-else-if="createMode" :context="context" :createMode="true" :configuration="configuration" />
    <div v-if="ready && newTransformation" class="if-aurora display-flex justify-content-center margin padding">
      <div class="flex-shrink-0">
        <f7-button class="padding-left padding-right" style="width: 150px" color="blue" large raised fill @click="createTransformation">
          Create Transformation Configuration
        </f7-button>
      </div>
    </div>

    <f7-fab v-show="!newTransformation && !configuration.content && context.mode === 'application/javascript' && !isBlockly" position="center-bottom" slot="fixed" color="blue" @click="convertToBlockly" text="Design with Blockly">
      <f7-icon f7="ticket_fill" />
    </f7-fab>

    <f7-sheet ref="detailsSheet" class="transformation-details-sheet" :backdrop="false" :close-on-escape="true" :opened="detailsOpened" @sheet:closed="detailsOpened = false">
      <f7-page>
        <f7-toolbar tabbar bottom>
          <span class="margin-left">Transformation details</span>
          <div class="right">
            <f7-link sheet-close class="padding-right">
              <f7-icon f7="chevron_down" />
            </f7-link>
          </div>
        </f7-toolbar>
        <f7-block class="block-narrow">
          <transformation-general-settings :context="context" :createMode="newTransformation" :configuration="configuration" />
          <f7-col v-if="isEditable">
            <f7-list>
              <f7-list-button color="red" @click="deleteTransformation">
                Remove Transformation
              </f7-list-button>
            </f7-list>
          </f7-col>
        </f7-block>
      </f7-page>
    </f7-sheet>
  </f7-page>
</template>

<style lang="stylus">
.transformation-editor.vue-codemirror
  display block
  top calc(var(--f7-navbar-height) + var(--f7-tabbar-height))
  height calc(100% - 2*var(--f7-navbar-height))
  width 100%
</style>

<script>
import DirtyMixin from '../dirty-mixin'
import TransformationGeneralSettings from '@/pages/settings/transformations/transformation-general-settings'

export default {
  mixins: [DirtyMixin],
  components: {
    TransformationGeneralSettings,
    'editor': () => import(/* webpackChunkName: "script-editor" */ '@/components/config/controls/script-editor.vue'),
    'blockly-editor': () => import(/* webpackChunkName: "blockly-editor" */ '@/components/config/controls/blockly-editor.vue')
  },
  props: ['transformationId', 'createMode'],
  data () {
    return {
      newTransformation: this.createMode,
      ready: false,
      loading: false,
      languages: null,
      configuration: {},
      context: {},
      transformation: '',
      keyHandler: null,
      detailsOpened: false,
      blocklyCodePreview: false
    }
  },
  computed: {
    pageTitle () {
      if (this.newTransformation) return 'Create Transformation Configuration'
      return 'Edit TransformationConfiguration'
    },
    isEditable () {
      return this.configuration && this.configuration.editable !== false
    },
    isBlockly () {
      return this.context && this.context.mode === 'blockly'
    }
  },
  methods: {
    onPageAfterIn () {
      if (this.ready) return
      if (this.createMode) {
        this.initializeNewTransformation()
        return
      }
      if (window) {
        window.addEventListener('keydown', this.keyDown)
      }
      this.load()
    },
    onPageBeforeOut () {
      this.$refs.detailsSheet.f7Sheet.close()
      if (window) {
        window.removeEventListener('keydown', this.keyDown)
      }
    },
    initializeNewTransformation () {
      this.configuration = {
        uid: this.$f7.utils.id(),
        label: '',
        type: '',
        language: null,
        content: '',
        context: '{}',
        editable: true
      }
      this.context = {}
      this.ready = true
    },
    createTransformation () {
      if (!this.configuration.uid) {
        this.$f7.dialog.alert('Please give an ID to the configuration')
        return
      }
      if (!this.configuration.type) {
        this.$f7.dialog.alert('Please give the type of to the transformation')
        return
      }
      if (!this.configuration.label) {
        this.$f7.dialog.alert('Please give a type for this configuration')
        return
      }

      this.configuration.uid = 'config:' + this.configuration.type + ':' + this.configuration.uid

      if (this.configuration.language) {
        this.configuration.uid += ':' + this.configuration.language
      }

      this.configuration.context = JSON.stringify(this.context)

      this.$oh.api.put('/rest/transformations/configurations/' + this.configuration.uid, this.configuration).then(() => {
        this.$f7.toast.create({
          text: 'Transformation created',
          destroyOnClose: true,
          closeTimeout: 2000
        }).open()
        this.$f7router.navigate(this.$f7route.url.replace('/add', '/' + this.configuration.uid), { reloadCurrent: true })
        this.newTransformation = false
        this.ready = false
        if (window) {
          window.addEventListener('keydown', this.keyDown)
        }
        this.load()
      })
    },
    load () {
      if (this.loading) return
      this.loading = true

      this.$oh.api.get('/rest/transformations/configurations/' + this.transformationId).then((data) => {
        this.$set(this, 'configuration', data)
        this.context = JSON.parse(data.context)

        console.log(this.context)

        this.loading = false
        this.ready = true
      })
    },
    save (noToast) {
      if (!this.isEditable) return
      if (this.isBlockly) {
        try {
          this.context.blockSource = this.$refs.blocklyEditor.getBlocks()
          this.configuration.content = this.$refs.blocklyEditor.getCode()
        } catch (e) {
          this.$f7.dialog.alert(e)
          return Promise.reject(e)
        }
      }
      this.configuration.context = JSON.stringify(this.context)
      return this.$oh.api.put('/rest/transformations/configurations/' + this.configuration.uid, this.configuration).then((data) => {
        this.dirty = false
        if (!noToast) {
          this.$f7.toast.create({
            text: 'Transformation configuration updated',
            destroyOnClose: true,
            closeTimeout: 2000
          }).open()
        }
      }).catch((err) => {
        this.$f7.toast.create({
          text: 'Error while saving transformation configuration: ' + err,
          destroyOnClose: true,
          closeTimeout: 2000
        }).open()
      })
    },
    deleteTransformation () {
      this.$f7.dialog.confirm(
        `Are you sure you want to delete ${this.configuration.uid}?`,
        'Delete Transformation',
        () => {
          this.$oh.api.delete('/rest/transformations/configurations/' + this.configuration.uid).then(() => {
            this.$f7router.back('/settings/transformations/', { force: true })
          })
        }
      )
    },
    showBlocklyCode () {
      try {
        this.context.blockSource = this.$refs.blocklyEditor.getBlocks()
        this.configuration.content = this.$refs.blocklyEditor.getCode()
        if (this.isBlockly) this.blocklyCodePreview = true
      } catch (e) {
        this.$f7.dialog.alert(e)
      }
    },
    convertToBlockly () {
      if ((this.configuration && this.configuration.content) || this.isBlockly || this.context.mode !== 'application/javascript') return
      this.$set(this.context, 'blockSource', '<xml xmlns="https://developers.google.com/blockly/xml"></xml>')
    },
    onEditorInput (value) {
      this.configuration.content = value
      this.dirty = true
    },
    keyDown (ev) {
      if ((ev.ctrlKey || ev.metaKey) && !(ev.altKey || ev.shiftKey)) {
        switch (ev.keyCode) {
          case 66:
            if (this.isBlockly) {
              if (this.blocklyCodePreview) {
                this.blocklyCodePreview = false
              } else {
                this.showBlocklyCode()
              }
            } else {
              this.convertToBlockly()
            }
            ev.stopPropagation()
            ev.preventDefault()
            break
          case 68:
            this.toggleDisabled()
            ev.stopPropagation()
            ev.preventDefault()
            break
          case 82:
            this.runNow()
            ev.stopPropagation()
            ev.preventDefault()
            break
          case 83:
            this.save()
            ev.stopPropagation()
            ev.preventDefault()
            break
        }
      }
    }
  }
}
</script>
